### ISSUE TITLE
Add "Unit Size (MW)" to Generators and Scheduled Loads (Generators and Scheduled Loads) table

### ISSUE THREAD

**Issue by dawkinsmw** [UNSW-CEEM/NEMOSIS#21]
Hi team
Would it be difficult/appropriate to add Unit Size (MW) to the Generators and Scheduled Loads table.
It is available in the raw NEM Registration and Exemption List.

**Comment by nick-gorman** [comment]
Hi @dawkinsmw 

Thanks for the suggestion, good know what data folks need.

The Generators and Scheduled Loads table is processed by NEMOSIS to aggregate duplicate rows for each DUID. However, in the raw format different rows for the same DUID can have different values for the Unit Size (MW) value. We haven't included this column because we weren't 100% sure on the best way to aggregate this data. It might need to be some weighted averaging considering also the Physical Unit No. to determine the number of unit that each row pertains to. If you have any thoughts on this we'd be happy to add the column if we can establish the correct aggregation methodology.

Cheers,
Nick

**Comment by dawkinsmw** [comment]
@nick-gorman 
Would the sum be appropriate? 
For example, Hallett Power Station, has the following entries:

</head>

Physical Unit No. | Unit Size (MW)
-- | --
GT 1-2,GT 1-4 | 14
GT 1-3 | 37
GT 2-1 | 15.5
GT 2-2 | 22.5
GT 2-3 | 25
GT 2-4 | 23.4
GT 3-1 | 15
GT 3-2 | 15.3
GT 3-3 | 15.5
GT 3-4 | 15.7
GT 4-1 | 15.1
GT 4-2 | 14.6
</body>

</html>


Which sum to 228.6MW close to the 235MW on the Energy Australia website: https://www.energyaustralia.com.au/about-us/energy-generation/hallett-power-station

The sum seems to be appropriate for a number of examples I checked by hand. For wind farms the sum of Reg Cap seems to be close to the advertised capacities. Potentially we could supply Unit Size, Reg Cap and Max Cap?

**Comment by nick-gorman** [comment]
@dawkinsmw 

Summing can give incorrect results in some cases. See the case of "Catagunya / Liapootah / Wayatinah Power Station", numbers below. Summing gives a total of 24 + 27.9 + 31.5 + 12.8 = 111.3. However, the registered capacity is 173.7. If we take the data to mean that units C1 and C2 both have a cap of 24, and units W1, W2, W3 have a cap of 12.8, then the maths is 2*24 + 27.9 + 31.5 + 13*2.8 = 173.7. A properly general solution would need to interpret the text in Physical Unit No. to determine how many units are being described.

| Physical Unit No. | Unit Size (MW) |
| C 1-2 | 24 |
| L 1 | 27.9 |
| L 2 | 27.9 |
| L 3 | 31.5 |
| W 1-3 | 12.8 |

I think it may just be safer to use the registered capacity. 

Also, something that I maybe should have mentioned before is that the registered and max capacity data is available in the table https://github.com/UNSW-CEEM/NEMOSIS/wiki/AEMO-Tables#dispatch-unit-detail-dudetail

**Comment by dawkinsmw** [comment]
Thanks @nick-gorman the dispatch-unit-detail-dudetail table was what I was looking for.
