### ISSUE TITLE
Static table download error

### ISSUE THREAD

**Issue by khalido** [UNSW-CEEM/NEMOSIS#8]
I'm trying to download the [static Generator table](https://github.com/UNSW-CEEM/NEMOSIS/wiki/AEMO-Tables#generators-and-scheduled-loads-generators-and-scheduled-loads) using the name `Generators and Scheduled Loads` with the code:

```
gen_table = "Generators and Scheduled Loads"
gen = data_fetch_methods.static_table(start_time, end_time, 
                                gen_table, raw_data_cache)
```
but it fails with:

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 0: invalid continuation byte
```

It works to fetch the pricing data:

```
# download pricing data
start_time = '2017/01/01 00:00:00' # start time, exclusive
end_time = '2017/01/31 23:59:00' # end time, inclusive
table = 'DISPATCHPRICE' # the table the data is requested from
raw_data_cache = 'data/raw_data_cache' # raw data is cached

df = data_fetch_methods.dynamic_data_compiler(start_time, end_time, table, raw_data_cache)
```
So not sure what I'm doing wrong for the static table. I'm using python 3 on Google colab.

**Comment by nick-gorman** [comment]
Hi khalido,

What version of NEMOSIS are you using?

**Comment by nick-gorman** [comment]
Hi khalido,

I've been able to replicate your error on the latest version.

To access this table you need to use the function data_fetch_methods.static_table_xl, because the data comes from AEMO in xls format. 

Also you may need to install the xlrd package as it seems I forgot to add this to the requirements. 

Lastly it seems there is a bug where this function won't work unless you specify the select_columns argument, so I've shown a work around below.

Let me know if this works for you.

`from nemosis import data_fetch_methods
from nemosis import defaults

gen_table = "Generators and Scheduled Loads"
raw_data_cache = 'data/raw_data_cache' # raw data is cached
gen = data_fetch_methods.static_table_xl('', '', gen_table, raw_data_cache, 
    select_columns=defaults.table_columns[gen_table])`

Cheers,
Nick

**Comment by khalido** [comment]
Hi, much thanks, it works now! I'm using the [1.3.1 version of nemosis on pip](https://pypi.org/project/nemosis/) and with your code above it works.

Still looking around the AEMO data, (for a uni project), thanks for nemosis, makes it a lot easier to use AEMO.
