### ISSUE TITLE
STPASA tables

### ISSUE THREAD

**Issue by khalido** [UNSW-CEEM/NEMOSIS#9]
Is it possible to download the [Stpasa tables](https://aemo.com.au/energy-systems/electricity/national-electricity-market-nem/nem-forecasting-and-planning/operational-forecasting/load-forecasting-in-pre-dispatch-and-stpasa)? I am specifically looking for `STPASA_REGIONSOLUTION`.

> AEMO must produce load forecasts for each region for the following timeframes:
> - Each day for the day ahead – pre-dispatch forecast
> - Each day for the period two to seven days ahead – short term projected assessment of system adequacy (STPASA) forecast

In this [AEMO data model report - pdf](http://nemweb.com.au/Data_Archive/Wholesale_Electricity/MMSDM/2018/MMSDM_2018_05/MMSDM_Historical_Data_SQLLoader/DOCUMENTATION/MMS%20Data%20Model/v4.27/MMS%20Data%20Model%20Report.pdf), its the `STPASA_REGIONSOLUTION` which is updated each STPASA run (i.e every 2 hours).

> STPASA_REGIONSOLUTION shows the results of the regional capacity,
maximum surplus reserve and maximum spare capacity evaluations for
each period of the study

**Comment by nick-gorman** [comment]
Hi khalido, 

The backend would probably support this but it requires adding some table specific settings in [defaults.py](https://github.com/UNSW-CEEM/NEMOSIS/blob/master/nemosis/defaults.py), [data_fetch_methods.py](https://github.com/UNSW-CEEM/NEMOSIS/blob/master/nemosis/data_fetch_methods.py), and [processing_info_maps.py](https://github.com/UNSW-CEEM/NEMOSIS/blob/master/nemosis/processing_info_maps.py). That assumes that these tables can be processed using the same settings as one of the existing tables.

If you clone the repository it should be reasonably straight forward to add them for your personal use.

Otherwise I can add them at some point, but it may take a while.

Cheers,
Nick

**Comment by prakaa** [comment]
Hi @khalido,

Probably quite late but a separate package now deals with this data - `nemseer`. It's very close to v1.0 and is thoroughly tested and documented. 

https://github.com/UNSW-CEEM/NEMSEER
